# Generated by Django 4.2.1 on 2023-05-12 18:32

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок:')),
                ('url', models.SlugField(verbose_name='URL-адрес(авто):')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Подробное описание:')),
                ('options', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Параметры содержания:')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото:')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания:')),
                ('keyword', models.CharField(default='123', max_length=200, verbose_name='Слова для поиска:')),
                ('author', models.ForeignKey(default=django.db.models.manager.BaseManager.all, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
            ],
            options={
                'verbose_name': 'Пост главной страницы',
                'verbose_name_plural': 'Посты на главной странице',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок:')),
                ('url', autoslug.fields.AutoSlugField(unique=True, verbose_name='URL-адрес(авто):')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание:')),
                ('image', models.ImageField(upload_to='forum', verbose_name='Фото:')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания поста:')),
                ('author', models.ForeignKey(default=django.db.models.manager.BaseManager.all, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
            ],
            options={
                'verbose_name': 'Пост на форуме',
                'verbose_name_plural': 'Посты на форуме',
            },
        ),
        migrations.CreateModel(
            name='CommentForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания:')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_forum', to='myblog.forumpost', verbose_name='Текст:')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_forum', to=settings.AUTH_USER_MODEL, verbose_name='Имя:')),
            ],
            options={
                'verbose_name': 'Комментарий под постом на форуме',
                'verbose_name_plural': 'Комментарии на форуме',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания:')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post', verbose_name='Текст:')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя:')),
            ],
            options={
                'verbose_name': 'Комментарий под постом главной страницы',
                'verbose_name_plural': 'Комментарии под постом главной страницы',
                'ordering': ['-created_date'],
            },
        ),
    ]
