# Generated by Django 4.2 on 2023-04-22 14:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(default='аквариум, рыбки', max_length=200)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.DeleteModel(
            name='Visual',
        ),
        migrations.AddField(
            model_name='commentforum',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_forum', to='myblog.forumpost'),
        ),
        migrations.AddField(
            model_name='commentforum',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_forum', to=settings.AUTH_USER_MODEL),
        ),
    ]
