# Generated by Django 4.1.7 on 2023-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_options',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
