# Generated by Django 4.1.7 on 2023-04-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_content_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_options',
        ),
    ]
