# Generated by Django 4.2 on 2023-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_commentforum_forumpost_delete_visual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Комментарий под постом главной страницы', 'verbose_name_plural': 'Комментарии под постом главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='commentforum',
            options={'ordering': ['-created_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии на форуме'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': 'Пост на форуме', 'verbose_name_plural': 'Посты на форуме'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост главной страницы', 'verbose_name_plural': 'Посты на главной странице'},
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='image',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='forum'),
        ),
    ]
