# Generated by Django 4.1.7 on 2023-04-02 19:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_post_content_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_options',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=20),
            preserve_default=False,
        ),
    ]
